### ISSUE TITLE
Plutus V3 cost plan testing

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#2]
### Task Details
 - Check if the cost of new primitives matches with what is defined in plutus, through making transactions
 - Check for each new primitives introduced in v3.

### Approach
-  List all the primitives and create plutus contracts for them.
-  Create a base contract where operations is to be added 
-  Compose transaction for each of the primitive and calculate the cost
- Calculate the difference and compare with the costs provided in plutus.
 
### Acceptance Criteria
- [ ] Tests are implemented
- [ ] A document or a report with all the primitives, cost and indication whether or not the value matches.

**Comment by spannercode** [comment]
- Lets verify the cost plan for reference scripts.
- Lets check the changes on cardano-node-tests existing tests that cover the cost plan (including the lastest reduction in costs for conway era for Plutus v2) whether or not it exists.
- Lets compare the costs for same contract on v2 and v3 and compare the cost params and test v3 costs are lower than v2.
- For the new primitives cost plan, I'll reach out to Martin and Ziyang again.

**Comment by reeshavacharya** [comment]
### Approach
- create a ref script for cardano-marketplace 
- calculate the size of the ref sctipt in bytes
- create tx to buy with ref script and calculate the ada required
- create tx to buy without ref script and calculate the ada required
- check whether the results adhere to ref script cost calculator

**Comment by reeshavacharya** [comment]
# Simple Market Efficiency Analysis

## V3 Script Performance Comparison

| **Type**  | **Script Bytes** | **Cost to Create Ref Script** | **Size of Tx to Create Ref Script** | **Cost to Withdraw Token Using Ref Script** | **Cost to Buy Token Using Ref Script** |
|-----------|------------------|------------------------------|-------------------------------------|--------------------------------------------|----------------------------------------|
| **Normal**| 8118             | 530,657                      | 8429                                | 402,933                                    | 456,318                                |
| **Lazy**  | 7125             | 486,965                      | 7436                                | 376,888                                    | 417,008                                |

---

## Calculation Details

> *Note: Total cost due to reference script is calculated as `tx_bytes * 15` since none of our reference scripts exceed 25,000 bytes.*

### Withdraw Using Reference Script

- **Script Size Difference:**  
    `8118 - 7125 = 993 bytes`
  
- **Observed Cost Difference to Withdraw:**  
    `402,933 - 376,888 = 26,045`
  
- **Estimated Cost Difference to Withdraw:**  
    `993 * 15 = 14,895`
  
- **Difference Between Estimated and Observed Cost:**  
    `26,045 - 14,895 = 11,150`

### Buy Using Reference Script

- **Script Size Difference:**  
    `8118 - 7125 = 993 bytes`
  
- **Observed Cost Difference to Buy:**  
    `456,318 - 417,008 = 39,310`
  
- **Estimated Cost Difference to Buy:**  
    `993 * 15 = 14,895`
  
- **Difference Between Estimated and Observed Cost:**  
    `39,310 - 14,895 = 24,415`

**Comment by reeshavacharya** [comment]
## V3 Script Performance

| **Type**  | **Script Bytes** | **Cost to Create Ref Script** | **Size of Tx to Create Ref Script** | **Cost to Withdraw Token Using Ref Script** | **Cost to Buy Token Using Ref Script** |
|-----------|------------------|------------------------------|-------------------------------------|--------------------------------------------|----------------------------------------|
| **Normal**| 8118             | 530,657                      | 8429                                | 402,933                                    | 456,318                                |
| **Super Lazy**  | 2573             | 285,093                      | 2848                                | 258,164                                    | 297,826                                |

## V2 Script Performance

| **Type**  | **Script Bytes** | **Cost to Create Ref Script** | **Size of Tx to Create Ref Script** | **Cost to Withdraw Token Using Ref Script** | **Cost to Buy Token Using Ref Script** |
|-----------|------------------|------------------------------|-------------------------------------|--------------------------------------------|----------------------------------------|
| **Normal**| 4594             | 374,017                      | 4869                                | 378,849                                    | 438,889                                |
| **Super Lazy**  | 2848             | 297,193                      | 3123                                | 298,732                                    | 334,188                                |



### Efficiency of Fees in withdraw Tx 

**Normal V2 vs Normal V3**
- (402933 - 378849) / 402933 = 0.0597 ~ 6%
- V2 is efficient by about 6%

**Super Lazy V2 vs Super Lazy V3**
- (298732 - 258164) / 298732 =  0.1358 ~ 13.6%
- V3 is effficient by about 13.6%


### Efficiency of Fees in buy Tx 

**Normal V2 vs Normal V3**
- (456318 - 438889) / 456318 = 0.03819 ~ 3.8% 
- V2 is efficient by about 3.8%

**Super Lazy V2 vs Super Lazy V3**
- (334188 - 297826) / 334188 = 0.1088 ~ 10.9%
- V3 is effficient by about 10.9%

**Comment by spannercode** [comment]
The above benchmark covers the cost model testing.
