### ISSUE TITLE
Issue Management Ticket

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#23]
Oversight and reporting on community issues raised through Cardano Node
Suggestion an amount of man-days used via call off / or % of the above to have as a call off

### Acceptance Criteria
- [x] Report on items seen, triaged and actions taken.
- [x] For each issue we triaged, lets add a comment on the issue that we have triaged the issue and is valid or not.

**Comment by spannercode** [comment]
The issues to be triaged are listed with tag `needs triage`.
https://github.com/IntersectMBO/cardano-node/issues?q=is%3Aissue+is%3Aopen+label%3A%22needs+triage%22

**Comment by spannercode** [comment]
For the bugs, lets have a comment like this:
We're able (or not) to reproduce the issue as reported by the issue author. We consider the impact of this issue to be ? because ?.

The goal is the node team should be able to prioritize the issue accordingly based on the comment.

**Comment by spannercode** [comment]
Here are the ticket on time was spend on triaging, reproducing or commenting on them:
https://github.com/IntersectMBO/cardano-node/issues/5899
https://github.com/IntersectMBO/cardano-node/issues/5906
https://github.com/IntersectMBO/cardano-node/issues/5934
https://github.com/IntersectMBO/cardano-node/issues/5985
https://github.com/IntersectMBO/cardano-node/issues/5963
https://github.com/IntersectMBO/cardano-node/issues/5930
https://github.com/IntersectMBO/ouroboros-network/issues/5006
https://github.com/IntersectMBO/cardano-cli/issues/886
https://github.com/IntersectMBO/cardano-node/issues/5984
https://github.com/IntersectMBO/cardano-node/issues/5968
https://github.com/IntersectMBO/cardano-node/issues/5931
https://github.com/IntersectMBO/cardano-node/issues/5926
https://github.com/IntersectMBO/cardano-node/issues/5925
https://github.com/IntersectMBO/cardano-node/issues/5908

Overall we couldn't find impact on new features for the conway era from the issues reported by the users.
