### ISSUE TITLE
Create Blog Post, with benchmark results like the one made for artano.

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#34]
Using the benchmark and test results for v2 and v3 contracts with/without reference script, Write a blogpost showing the progresses made in PlutusV3 in context of a marketplace contract.

#### Acceptance Criteria
- [x] Blogpost content is created.
- [x] Blogpost is published in ~cardano-essentials~ Github publicly

**Comment by spannercode** [comment]
This is the final document that will be shared with the community from Intersect side:

https://github.com/cardanoapi/hardfork-testing/blob/main/migration.md
