### ISSUE TITLE
Ledger-Nano-S-Plus Wallet Validation

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#42]
We have acquired Ledger-Nano-S-Plus

This ticket involves testing of following on the Ledger Nano
- [x] Acquiring the latest version of cardano-app or firmware for ledger
- [x] Stake registration
- [x] SPO Delegation
- [x] Voting Delegation (abstain , no-confidence , drep_id)
- [x] Drep registration
- [x] CC registration
- [x] Voting on proposals as drep
- [x] Voting on proposals as cc

**Comment by mesudip** [comment]
TODO: waiting for new firmware. How do we use it in testnet?

**Comment by reeshavacharya** [comment]
The ledger nano s plus has been tested on mainnet and sanchonet.
Reported in google docs: https://docs.google.com/document/d/1nt2BX7GSvNmPYw2O4VmIpn14shJUQb-evyzUpAqggHs/edit?usp=sharing
