### ISSUE TITLE
[ Cost Plan ] Opportunity to uplift reference scripts

### ISSUE THREAD

**Issue by mesudip** [cardanoapi/hardfork-testing#5]
Reference scripts usage in v1/v2 used in v2 vs v3.

**Comment by mesudip** [comment]
TODO check reference script usage in v1 contract.

**Comment by spannercode** [comment]
For the scope of this ticket, lets consider the costs implication of the reference scripts in v1, v2, v3.

**Comment by reeshavacharya** [comment]
- The usage of reference scripts in V1 contracts is tested within the Cardano Marketplace project. The detailed [**Test Results**](https://github.com/dQuadrant/cardano-marketplace/blob/main/reports/test-sanchonet-cardano-api-9.0.0/2024-08-07_09-38-46-transaction-report.md) is in the Marketplace repository.

- For testing the reference script cost calculator:
  - The test repository can be found at [**cardanoapi/cost-model-test**](https://github.com/cardanoapi/cost-model-test).
  - The testing procedure is documented in the [**verification procedure**](https://github.com/cardanoapi/cost-model-test/blob/main/docs/verification-procedure.md).
  - The corresponding test [**report and logs**](https://github.com/cardanoapi/cost-model-test/blob/main/report/2024-08-23_08-15-10-transaction-bench.log) are available in the same repository.
